<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header'); ?>

<div class="container">
    <br>
    <div class="jumbotron">
        <center><img src="http://localhost/weblogic_2020/public/img/jogador.png" alt="profile_image" style="width:200px;"></center>

        <hr>

        <div class="container text-center">



        </div>

        
    </div>
</div>

<?php Layout::includeLayout('footer')?>