<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header'); ?>

<div class="container">
    <br>
    <article class="col-xs-12 maincontent">

				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="thin text-center">Mudar password</h3>
							
							<hr>
							
							<form method="post" id="changepassword" action="">
								<div class="top-margin" >
									<label>Password</label>
									<input type="text" class="form-control" id="password" name="password">
								</div>
								<div class="top-margin" >
									<label>Nova Password </label>
									<input type="password" class="form-control" id="new_password" name="new_password">
									<small id="Error" class="text-danger"></small>
								</div>

								<hr>
									<center>
										<button class="btn btn-action" id="changePasswordSubmit">Mudar Password</button>
									</center>

							</form>
						</div>
					</div>

				</div>
				
			</article>
</div>

<?php Layout::includeLayout('footer')?>