<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header'); ?>

<div class="container">
    <br>
    <div class="jumbotron">
        <center><img src="http://localhost/weblogic_2020/public/img/jogador.png" alt="profile_image" style="width:200px;"></center>

        <hr>

        <div class="container text-center">
			<form method="post" id="changepassword" action="<?=Url::toRoute('home/changepasswordvalidation')?>">
				<div class="top-margin" >
					<label>Nova Password</label>
					<input type="password" class="form-control" id="password" name="password">
					<small id="passwordError" class="text-danger"></small>
				</div>
				<div class="top-margin" >
					<label>Repetir Password</label>
					<input type="password" class="form-control" id="repeat_password" name="repeat_password">
					<small id="repeatError" class="text-danger"></small>
				</div>

				<hr>
					<center>
						<button class="btn btn-action" id="changePasswordSubmit">Mudar Password</button>
					</center>

			</form>


        </div>

        
    </div>
</div>

<script>
$( "#changePasswordSubmit" ).click(function(e) {
	e.preventDefault();

	$('#passwordError').text('');
	$('#repeatError').text('');
	
	var password= $('#password').val();
	var repeat_password=$('#repeat_password').val();
	var checker= 0;

 	if(password.length <1){
		$('#passwordError').text('Preencha o campo');
		var checker=1;
	}
	else if(password.length>20 || password.length<8){
		$('#passwordError').text('O campo tem de ter no minimo 8 caracteres e no máximo 20');
		var checker=1;
	}
	else if(repeat_password.length<1){
		$('#repeatError').text('Preencha o campo');
		var checker=1;
	}
	else if(password!=repeat_password){
		$('#repeatError').text('Os campos não estão iguais');
		var checker=1;
	}

	
	if(checker==0){
		$('#changepassword').submit();
	}
	
});
</script>

<?php Layout::includeLayout('footer')?>