<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header'); ?>
<style>
    body{
        background:#181015;
        background-image: url('http://localhost/weblogic_2020/public/img/background-dice.jpg')!important;
        background-size: cover !important;
        
        background-repeat: no-repeat;

    }
</style>
    <!-- Header -->
    <header id="head">
        <div class="container">
            <div class="row">
                <?php if(!empty($succesregister)){echo "ola";}?>
                <h1 class="lead"><b>ShutTheBox</b><br><small>WebLogic MVC</small></h1>
                <p><a class="btn btn-action btn-lg" role="button" href="<?= Url::toRoute('home/login')?>">Login/Registar</a></p>

            </div>
        </div>
    </header>
    <!-- /Header -->


    <!-- Intro -->


</div>	<!-- /container -->

<?php Layout::includeLayout('footer')?>