<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Post;

Layout::includeLayout('header') ?>

	<!-- container -->
	<div class="container">


		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Login</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="thin text-center">Efetuar Login</h3>
							
							<hr>
							
							<form method="post" id="loginform" action="<?= URL::toRoute('home/loginvalidation')?>">
								<div class="top-margin" id="usernamepart">
									<label>Username <span class="text-danger">*</span></label>
									<input type="text" class="form-control" id="username" name="username">
									<small id="usernameError" class="text-danger"></small>
								</div>
								<div class="top-margin" id="passwordpart">
									<label>Password <span class="text-danger">*</span></label>
									<input type="password" class="form-control" id="password" name="password">
									<small id="passwordError" class="text-danger"></small>
								</div>

								<hr>

								<div class="row">
									<div class="col-lg-8">
									<a href="<?= URL::toRoute('home/register')?>">Criar uma conta</a>
									</div>
									<div class="col-lg-4 text-right">
										<button class="btn btn-action" id="loginFormSubmit"type="submit">Login</button>
									</div>
								</div>
								<?Php if(!empty($faillogin)){echo "ola";}?>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->
	<script>
	$( "#loginform" ).submit(function( e ) {
		e.preventDefault();
		var username= $('#username').val();
		var password= $('#password').val();
		var checker= 0;

		
		if(username.length <1){
			$('#usernameError').text('Preencha o campo');
			var checker=1;

		}
		else if(password.length <1){
			$('#passwordError').text('Preencha o campo');
			var checker=1;
		}
		else{
			var checker=0;
		}

		if(checker==0){
			var loginData = $('#loginform').serialize();
        	//alert(budgetData);

         $.ajax({
                type: 'POST',
                url: '<?=  URL::toRoute('home/loginvalidation') ?>', 
                cache: false,    
                data: loginData,
                success: function(data){  
				
                   if(data=='username and password error'){
						
						$('#passwordError').text('Nome de utilizador ou password incorretos');
				   }
				   if(data=='password error'){
						$('#passwordError').text('Password incorreta');
				   }
				   else{
						$('#loginform').submit();
				   }
                   
                   
                }
			});
			return false;
            
		}

	});


	</script>


<?php Layout::includeLayout('footer') ?>