<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header'); ?>
<?php $user = Data::get('users') ?>
<?php $error = Data::get('error'); ?>
<div class="container">
    <br>
    <div class="jumbotron">
        <center><img src="http://localhost/weblogic_2020/public/img/jogador.png" alt="profile_image" style="width:200px;"></center>

        <hr>

        <div class="container text-center">

            <h4><b>Username : </b><?php echo $user['username'];?></h4>
            <h4><b>Nome Completo : </b><?php echo $user['nome_completo'];?></h4>
            <h4><b>Email : </b><?php echo $user['email'];?></h4>
            <h4><b>Data de nascimento : </b><?php echo $user['birthday'];?></h4>
            <h4><b>Data de criação : </b><?php echo $user['created_date']->format('d-m-Y');?></h4>
            <a href="<?=Url::toRoute('home/editprofile')?>" class="btn btn-warning" role="button">Editar perfil</a>
            <a href="<?=Url::toRoute('home/changepassword')?>" class="btn btn-info" role="button">Mudar password</a>

        </div>

        
    </div>
</div>

<?php Layout::includeLayout('footer')?>