<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Post;

Layout::includeLayout('header') ?>

	<!-- container -->
	<div class="container">


		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Registar</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="thin text-center">Criar conta</h3>
							
							<hr>
							
							<form method="post" id="registerform" action="<?= URL::toRoute('home/registervalidation')?>">
								<div class="top-margin">
									<label>Username <span class="text-danger">*</span></label>
									<input type="text" class="form-control" id="username" name="username">
									<small id="usernameError" class="text-danger"></small>
								</div>
								<div class="top-margin">
									<label>Email <span class="text-danger">*</span></label>
									<input type="email" class="form-control" id="email" name="email">
									<small id="emailError" class="text-danger"></small>
								</div>
								<div class="top-margin">
									<label>Password <span class="text-danger">*</span></label>
									<input type="password" class="form-control" id="password" name="password">
									<small id="passwordError" class="text-danger"></small>
								</div>
								<div class="top-margin">
									<label>Repetir password <span class="text-danger">*</span></label>
									<input type="password" class="form-control" id="repeat_password" name="repeat_password">
									<small id="repeatError" class="text-danger"></small>
								</div>

								<hr>

								<div class="row">
									<div class="col-lg-8">
									<a href="<?= URL::toRoute('home/login')?>">Efetuar login</a>
									</div>
									<div class="col-lg-4 text-right">
										<button class="btn btn-action" type="submit">Registo</button>
									</div>
								</div>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->
	<script>
	$( "#registerform" ).submit(function( e ) {
		e.preventDefault();
		var username= $('#username').val();
		var email=$('#email').val();
		var password= $('#password').val();
		var repeat_password=$('#repeat_password').val();
		var checker= 0;

		
		if(username.length <1){
			$('#usernameError').text('Preencha o campo');
			var checker=1;

		}
		else if(email.length <1){
			$('#emailError').text('Preencha o campo');
			var checker=1;
		}
		else if(password.length <1){
			$('#passwordError').text('Preencha o campo');
			var checker=1;
		}
		else if(repeat_password.length<1){
			$('#repeatError').text('Preencha o campo');
			var checker=1;
		}
		else if(password!=repeat_password){
			$('#repeatError').text('Os campos não estão iguais');
			var checker=1;
		}
		else{
			var checker=0;
		}



		if(checker==0){
			var loginData = $('#registerform').serialize();
        	//alert(budgetData);

         $.ajax({
                type: 'POST',
                url: '<?=  URL::toRoute('home/registervalidation') ?>', 
                cache: false,    
                data: loginData,
                success: function(data){  
				
                   if(data==''){
						
						$('#passwordError').text('Nome de utilizador ou password incorretos');
				   }
				   else if(data=='password error'){
						$('#passwordError').text('Password incorreta');
				   }
				   else{
						$('#loginform').submit();
				   }
                   
                   
                }
			});
			return false;
            
		}

		

	});

	</script>

<?php Layout::includeLayout('footer') ?>