<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Post;

Layout::includeLayout('header') ?>

	<!-- container -->
	<div class="container">


		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Registar</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="thin text-center">Criar conta</h3>
							<hr>
							
							<form method="post" id="registerform" action="<?= URL::toRoute('home/registervalidation')?>">
								<div class="top-margin">
									<label>Username <span class="text-danger">*</span></label>
									<input type="text" class="form-control" id="username" name="username">
									<small id="usernameError" class="text-danger"></small>
								</div>
								<div class="top-margin">
									<label>Nome completo <span class="text-danger">*</span></label>
									<input type="text" class="form-control" id="nome_completo" name="nome_completo">
									<small id="nomeError" class="text-danger"></small>
								</div>
								<div class="top-margin">
									<label>Data de nascimento <span class="text-danger">*</span></label>
									<input type="date" class="form-control" id="birthday" name="birthday">
									<small id="dateError" class="text-danger"></small>
								</div>
								
								<div class="top-margin">
									<label>Email <span class="text-danger">*</span></label>
									<input type="email" class="form-control" id="email" name="email">
									<small id="emailError" class="text-danger"></small>
								</div>
								<div class="top-margin">
									<label>Password <span class="text-danger">*</span></label>
									<input type="password" class="form-control" id="password" name="password">
									<small id="passwordError" class="text-danger"></small>
								</div>
								<div class="top-margin">
									<label>Repetir password <span class="text-danger">*</span></label>
									<input type="password" class="form-control" id="repeat_password" name="repeat_password">
									<small id="repeatError" class="text-danger"></small>
								</div>

								<hr>

								<div class="row">
									<div class="col-lg-8">
									<a href="<?= URL::toRoute('home/login')?>">Já tem uma conta? Fazer Login</a>
									</div>
									<div class="col-lg-4 text-right">
										<button class="btn btn-action" id="registerFormSubmit">Registo</button>
									</div>
								</div>
                                <br>
								<br>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->
	<script>
	$( "#registerFormSubmit" ).click(function(e) {
		e.preventDefault();

		$('#usernameError').text('');
		$('#emailError').text('');
		$('#nomeError').text('');
		$('#dateError').text('');
		$('#passwordError').text('');
		$('#repeatError').text('');
		
		var username= $('#username').val();
		var nome_completo= $('#nome_completo').val();
		var birthday= $('#birthday').val();
		var email=$('#email').val();
		var password= $('#password').val();
		var repeat_password=$('#repeat_password').val();
		var checker= 0;

		
		if(username.length <1){
			$('#usernameError').text('Preencha o campo');
			var checker=1;

		}
		else if(nome_completo.length <1){
			$('#nomeError').text('Preencha o campo');
			var checker=1;
		}
		else if(birthday.length <1){
			$('#dateError').text('Preencha o campo');
			var checker=1;
		}
		else if(email.length <1){
			$('#emailError').text('Preencha o campo');
			var checker=1;
		}
		else if(password.length <1){
			$('#passwordError').text('Preencha o campo');
			var checker=1;
		}
		else if(password.length>20 || password.length<8){
			$('#passwordError').text('O campo tem de ter no minimo 8 caracteres e no máximo 20');
			var checker=1;
		}
		else if(repeat_password.length<1){
			$('#repeatError').text('Preencha o campo');
			var checker=1;
		}
		else if(password!=repeat_password){
			$('#repeatError').text('Os campos não estão iguais');
			var checker=1;
		}
		else{
			var checker=0;
			
		}
		var registerData = $('#registerform').serialize();

		if(checker==0){
			
        	//alert(budgetData);

         $.ajax({
                type: 'POST',
                url: '<?=  URL::toRoute('home/registervalidation') ?>', 
                cache: false,    
                data: registerData,
                success: function(data){  

                   if(data=='username error'){
						
						$('#usernameError').text('Nome de utilizador já existe');
				   }
				   else if(data=='email error'){
						$('#emailError').text('Email já existe');
				   }
				   else{
						/* $('#registerform').submit(); */
						window.location.replace("http://localhost/weblogic_2020/index");

				   }

                   
                }
			});
			return false;
            
		}

		

	});

	</script>

<?php Layout::includeLayout('footer') ?>