<footer id="footer" class="top-space" style="position:fixed;bottom:0px;width:100%;">

<div class="footer2">
    <div class="container">
        <div class="row">

            <div class="col-md-8 widget">
                <div class="widget-body">
                    <p class="simplenav">
                        <p>Projeto para a disciplina de programação php para web servidor</p>
                    </p>
                </div>
            </div>

            <div class="col-md-4 widget">
                <div class="widget-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <p class="text-left" >
                            Site criado por Rodolfo Barreira, Tiago Santos e Cidália Pinto
                            </p>
                        </div>
                        <div class="col">
                            <p style>
                                Copyright &copy; 2016-2017, Silvio Priem Mendes, PhD. <br> Site template by Sergey Pozhilov.
                            </p>
                        </div>
                    </div>
                </div>
            </div>

        </div> <!-- /row of widgets -->
    </div>
</div>

</footer>

<!-- JavaScript libs are placed at the end of the document so the pages load faster -->

<?php
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\Facades\DebugRenderer;
?>

<?=AssetBundler::js()?>

<script>hljs.initHighlightingOnLoad();</script>

</body>
</html>