<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $users = Data::get('backoffice')?>
<?php ErrMgr::attach($users) ?>


	<!-- container -->
	<div class="container">

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">New user</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<hr>
							<form method="post" action="<?=Url::toRoute('backoffice/store')?>">
								<div class="top-margin">
                                    <label>username <span class="text-danger"></span></label>
									<input type="text" value="<?=$users->username?>" name="username" class="form-control" placeholder="Enter name">
                                    <label>email <span class="text-danger"></span></label>
                                    <input type="text" value="<?=$users->email?>" name="email" class="form-control" placeholder="Enter email">
                                    <label>password <span class="text-danger"></span></label>
                                    <input type="text" value="<?=$users->password?>" name="password" class="form-control" placeholder="Enter password">


                                    <?= ErrMgr::bind('username');?>
                                    <?= ErrMgr::bind('email');?>
                                    <?= ErrMgr::bind('password') ?>

								</div>


								<hr>

									<div class="col-lg-4 text-right">
										<button class="btn btn-action" type="submit">create</button>
									</div>
								</div>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>