<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $users = Data::get('backoffice') ?>
<?php ErrMgr::attach($users) ?>

	<!-- container -->
	<div class="container">

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Update</h1>
				</header>
				

					<div class="panel panel-default">
						<div class="panel-body">

                            <hr>


							<form class="form-horizontal" method="post" action="<?=Url::toRoute('backoffice/update', $users->id)?>">

                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="name">Name:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
                                        <input type="text" value="<?=$users->username?>" class="form-control" required name="username" placeholder="username">
                                        <?= ErrMgr::bind('username') ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="name">ISBN:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
                                        <input type="text" required value="<?=$users->email?>" class="form-control" name="email" placeholder="email">
                                        <?= ErrMgr::bind('email') ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="name">password:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
                                        <input type="text" required value="<?=$users->password?>" class="form-control" name="password" placeholder="password">
                                        <?= ErrMgr::bind('password') ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="name">status:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
                                        <input type="text" required value="<?=$users->status?>" class="form-control" name="status" placeholder="status">
                                        <?= ErrMgr::bind('status') ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="name">role:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
                                        <input type="text" required value="<?=$users->role?>" class="form-control" name="role" placeholder="role">
                                        <?= ErrMgr::bind('status') ?>
                                    </div>
                                </div>

								<hr>

									<div class="col-lg-4 text-right">
										<button class="btn btn-action" type="submit">Save</button>
									</div>


								</div>
							</form>
						</div>
					</div>


				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>