<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $users = Data::get('backoffice') ?>

	<!-- container -->
	<div class="container">

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">info</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<hr>
							
							<form method="post" action="<?=Url::toRoute('backoffice/index')?>">
								<div class="top-margin">
									<label>username <span class="text-danger">*</span></label>
									<input readonly="true" type="text" value="<?=$users->username?>" name="username" class="form-control">
								</div>
								<div class="top-margin">
									<label>email <span class="text-danger">*</span></label>
									<input readonly="true" type="text" value="<?=$users->email?>" name="email" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>password <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$users->password?>" name="password" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>status <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?php
                                    if ($users->status==1){
                                        echo "Ativo";
                                    }else{
                                        echo "Banido";
                                    }?>" name="status" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>role <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?php
                                    if ($users->role==1){
                                        echo "Utilizador";
                                    }else{
                                        echo "Admin";
                                    }?>" name="role" class="form-control">
                                </div>

                                <hr>

									<div class="col-lg-4 text-right">
										<button class="btn btn-action" type="submit">Return</button>
									</div>
								</div>
                        <br><br><br><br>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>