<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;



Layout::includeLayout('header'); ?>
<head>
<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>

</head>


<div class="col-xs-12 col-sm-8 col-md-8 col-md-offset-2">
<div class="game-container center-block col-8" >
                <div class="row center-block ">
                    <div class="col-xs-2">
                        <div class="score-current" id="r1">
                            <div class="price" id="p1c1">1</div>
                        </div>
                        <div class="score-current" id="r2">
                            <div class="price" id="p1c2">2</div>
                        </div>
                        <div class="score-current" id="r3">
                            <div class="price" id="p1c3">3</div>
                        </div>
                        <div class="score-current" id="r4">
                            <div class="price" id="p1c4">4</div>
                        </div>
                        <div class="score-current" id="r5">
                            <div class="price" id="p1c5">5</div>
                        </div>
                        <div class="score-current" id="r6">
                            <div class="price" id="p1c6">6</div>
                        </div>
                        <div class="score-current" id="r7">
                            <div class="price" id="p1c7">7</div>
                        </div>
                        <div class="score-current" id="r8">
                            <div class="price" id="p1c8">8</div>
                        </div>
                        <div class="score-current" id="r9">
                            <div class="price" id="p1c9">9</div>
                        </div>
                    </div>
                    <div class="col-xs-5">
                        <div class="row">
                            <div class="col-xs-6">
                                <div class="player-cell">
                                    <img src="<?= Asset::image('jogador.png')?>" id="p1i" alt="Player" class="center-block">
                                    <div class="wrapper">
                                        <div style="display: block;" class="caption post-content finalmsg" id="p1msgdiv">&nbsp;</div>
                                    </div>
                                </div>
                                <div class="round-cell">
                                    <div class="price1" id="p1r"></div>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <div class="player-cell">
                                    <img src="<?= Asset::image('pc.png')?>" id="p2i" alt="Computer" class="center-block">
                                    <div class="wrapper">
                                        <div style="display: block;" class="caption post-content finalmsg" id="p2msgdiv">&nbsp;</div>
                                    </div>
                                </div>
                                <div class="round-cell">
                                    <div class="price1" id="p2r"></div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <form id="dice_roll_form" method="post" >
                                    <button id="dicebutton"   class="btn btn-md btn-primary center-block" >Roll Dice </button>
                                    <input type="text" name="dice1" id="dice1" value="<?php if(!empty($dice1)){echo $dice1;}?>" >
                                    <input type="text" name="dice2" id="dice2" value="<?php if(!empty($dice2)){echo $dice2;}?>" >

                                </form>                                
                            </div>
                            
                        </div>
                      
                        <div class="row"></div>
                        <div class="row center-block">
                            <div class="col-xs-6 col-xs-offset-3">
                                <div class="dicecell" id="d1" method="get" action="  <?=Url::toRoute('game/dado1')?>  ">
                                    <?php
                                    if(!empty($dado1)){
                                        if($dado1==1){
                                            ?>
                                            <img id="dice1" class="img-responsive die" src="<?= Asset::image('Dice/dieWhite1.png')?>" alt="Die 1">
                                            <input type="hidden" id="dice1-check" value="">
                                            <?php
                                        }
                                        if($dado1==2){
                                            ?>
                                            <img id="dice2" class="img-responsive die" src="<?= Asset::image('Dice/dieWhite2.png')?>" alt="Die 2">
                                            <input type="hidden" id="dice2-check" value="">
                                            <?php
                                        }
                                        if($dado1==3){
                                            ?>
                                            <img id="dice3" class="img-responsive die" src="<?= Asset::image('Dice/dieWhite3.png')?>" alt="Die 3">
                                            <input type="hidden" id="dice3-check" value="">
                                            <?php
                                        }
                                        if($dado1==4){
                                            ?>
                                            <img id="dice4" class="img-responsive die" src="<?= Asset::image('Dice/dieWhite4.png')?>" alt="Die 4">
                                            <input type="hidden" id="dice4-check" value="">
                                            <?php
                                        }
                                        if($dado1==5){
                                            ?>
                                            <img id="dice5" class="img-responsive die" src="<?= Asset::image('Dice/dieWhite5.png')?>" alt="Die 5">
                                            <input type="hidden" id="dice5-check" value="">
                                            <?php
                                        }
                                        if($dado1==6){
                                            ?>
                                            <img id="dice6" class="img-responsive die" src="<?= Asset::image('Dice/dieWhite6.png')?>" alt="Die 6">
                                            <input type="hidden" id="dice6-check" value="">
                                            <?php
                                        }
                                    }
                                    
                                    ?>
                                </div>
                                <div class="dicecell" id="d2" method="get" action="  <?=Url::toRoute('game/dado2') ?> ">

                                    <?php
                                    if(!empty($dado2)){
                                        if($dado2==1){
                                            ?>
                                            <img id="dice1" class="img-responsive die" src="<?= Asset::image('Dice/dieWhite1.png')?>" alt="Die 1">
                                            <?php
                                        }
                                        if($dado2==2){
                                            ?>
                                            <img id="dice1" class="img-responsive die" src="<?= Asset::image('Dice/dieWhite2.png')?>" alt="Die 2">
                                            <?php
                                        }
                                        if($dado2==3){
                                            ?>
                                            <img id="dice1" class="img-responsive die" src="<?= Asset::image('Dice/dieWhite3.png')?>" alt="Die 3">
                                            <?php
                                        }
                                        if($dado2==4){
                                            ?>
                                            <img id="dice1" class="img-responsive die" src="<?= Asset::image('Dice/dieWhite4.png')?>" alt="Die 4">
                                            <?php
                                        }
                                        if($dado2==5){
                                            ?>
                                            <img id="dice1" class="img-responsive die" src="<?= Asset::image('Dice/dieWhite5.png')?>" alt="Die 5">
                                            <?php
                                        }
                                        if($dado2==6){
                                            ?>
                                            <img id="dice1" class="img-responsive die" src="<?= Asset::image('Dice/dieWhite6.png')?>" alt="Die 6">
                                            <?php
                                        }
                                    }
                                    
                                    ?>
                                </div>
                            </div>
                            <div class="row" id="appenddice"></div>
                        </div>
                        <div id="novoJogo" class="col-xs-12">

                <!-- verificar se têm uma sessão de jogo-->
                <?php if(empty($_SESSION['game'])){?>
                    <form method="post" action="<?= Url::toRoute('game/game') ?>">
                        <button class="btn btn-success center-block">Novo Jogo</button>
                    </form>
                <?php }?>
            </div>
                        </div>
                    <div class="col-xs-1">
                        <div class="score-current1" id="r11">
                            <div class="price" id="p2c1">1</div>
                        </div>
                        <div class="score-current1" id="r12">
                            <div class="price" id="p2c2">2</div>
                        </div>
                        <div class="score-current1" id="r13">
                            <div class="price" id="p2c3">3</div>
                        </div>
                        <div class="score-current1" id="r14">
                            <div class="price" id="p2c4">4</div>
                        </div>
                        <div class="score-current1" id="r15">
                            <div class="price" id="p2c5">5</div>
                        </div>
                        <div class="score-current1" id="r16">
                            <div class="price" id="p2c6">6</div>
                        </div>
                        <div class="score-current1" id="r17">
                            <div class="price" id="p2c7">7</div>
                        </div>
                        <div class="score-current1" id="r18">
                            <div class="price" id="p2c8">8</div>
                        </div>
                        <div class="score-current1" id="r19">
                            <div class="price" id="p2c9">9</div>
                        </div>
                    </div>
                </div>

                <div id="some-element" style="display: none;">
                    <div class="stackbox-body">Stackbox example with options</div>
                </div>
                <!--
                <div class="row center-block">
                    <div class="col-xs-12">
                        <a target="_blank" href="http://www.playonlinedicegames.com"><img src="http://localhost/weblogic_2020/public/img/verde-lodo.jpg" class="img-responsive center-block"></a>
                    </div>
                </div>-->
            </div>
            
</div>
<script>
    $( "#dicebutton" ).click(function(e) {
		e.preventDefault();
        //prevenir que dê submit. caso haja erros ele não previne e dá bug. convem ter em atençao
        var playerdice1=$('#dice1').val();
        var playerdice2=$('#dice2').val();
        var enemydice1='';
        var enemydice1='';
/*          $.ajax({
                type: 'POST',
                url: '<?=  URL::toRoute('game/randomdice') ?>', 
                cache: false,    
                data: {dice1:1} ,
                success: function(data){  

                   alert(data);

                   
                }
			}); */
			var playerdice1=Math.floor(Math.random() * 6) + 1  
            var playerdice2=Math.floor(Math.random() * 6) + 1  
            $('#dice1').val(playerdice1);
            $('#dice2').val(playerdice2);

            var html="<div class='col-md-4'>";
            html+="<img  src='http://localhost/weblogic_2020/public/img/diceplayer"+playerdice1+".png' >";
            html+="</div>";
            html+="<div class='col-md-4'>";
            html+="<img  src='http://localhost/weblogic_2020/public/img/diceplayer"+playerdice2+".png' >";
            html+="</div>";
            $('#appenddice').html(html);
		

	});
</script>


