<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;




Layout::includeLayout('header'); ?>
<head>
<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>

</head>

<body>
<div class="col-xs-10 col-xs-offset-2">
<div class="game-container   center-block col-xs-10" >
                <div class="row center-block  ">
                    <div class="col-xs-2">
                        <div class="score-current" id="r1">
                            <button class="price" id="point1" onclick="checkifpossible(1)" disabled>1</button>
                        </div>
                        <div class="score-current" id="r1">
                            <button class="price" id="point2" onclick="checkifpossible(2)" disabled>2</button>
                            </div>
                        <div class="score-current" id="r1">
                            <button class="price" id="point3" onclick="checkifpossible(3)" disabled>3</button>
                            </div>
                        <div class="score-current" id="r1">
                            <button class="price" id="point4" onclick="checkifpossible(4)" disabled>4</button>
                            </div>
                        <div class="score-current" id="r1">
                            <button class="price" id="point5" onclick="checkifpossible(5)" disabled>5</button>
                            </div>
                        <div class="score-current" id="r1">
                            <button class="price" id="point6" onclick="checkifpossible(6)" disabled>6</button>
                            </div>
                        <div class="score-current" id="r1">
                            <button class="price" id="point7" onclick="checkifpossible(7)" disabled>7</button>
                            </div>
                        <div class="score-current" id="r1">
                            <button class="price" id="point8" onclick="checkifpossible(8)" disabled>8</button>
                            </div>
                        <div class="score-current" id="r1">
                            <button class="price" id="point9" onclick="checkifpossible(9)" disabled>9</button>
                            
                        </div>
                        <button class="btn btn-success center-block" id="gameover" disabled>GAME OVER</button>

                    </div>
                    <div class="col-xs-8">
                        <div class="row">
                            <div class="col-xs-6">
                                <div class="player-cell">
                                    <img src="<?= Asset::image('jogador.png')?>" id="p1i" alt="Player" class="center-block">
                                    <div class="wrapper">
                                        <div style="display: block;" class="caption post-content finalmsg" id="p1msgdiv">&nbsp;</div>
                                    </div>
                                </div>
                                <div class="round-cell ">
                                    <input class="price2 " id="pontosfinais" value="" readonly>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <div class="player-cell">
                                    <img src="<?= Asset::image('pc.png')?>" id="p2i" alt="Computer" class="center-block">
                                    <div class="wrapper">
                                        <div style="display: block;" class="caption post-content finalmsg" id="p2msgdiv">&nbsp;</div>
                                    </div>
                                </div>
                                <div class="round-cell">
                                    <div class="price2" id="p2r"></div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <form id="dice_roll_form" method="post" >
                                    <button id="dicebutton"   class="btn btn-md btn-primary center-block" >Roll Dice </button>
                                    <input type="hidden" name="dice1" id="dice1" value="<?php if(!empty($dice1)){echo $dice1;}?>" readonly>
                                    <input type="hidden" name="dice2" id="dice2" value="<?php if(!empty($dice2)){echo $dice2;}?>" readonly>
                                    <label for="sumpoints" style="color:white">Pontos ainda possíveis para jogar</label>
                                    <input type="text" style="width:40px;text-align:center" name="sumpoints" id="sumpoints" value="0" readonly>
                                    <input type="hidden" name="winGame" id="winGame" value="" readonly>

                                    <input type="hidden" name="playerpoints" id="playerpoints" value="" readonly>
                                    <div id="appendselected"></div>
                                    

                                </form>                                
                            </div>
                            
                        </div>
                      
                        <div class="row"></div>
                        <div class="row center-block">
                            <div class="col-xs-6 col-xs-offset-3">
                               
                            </div>
                            <div class="row" id="appenddice"></div>
                        </div>
                        <div id="novoJogo" class="col-xs-12">

                <!-- verificar se têm uma sessão de jogo-->
                <?php if(empty($_SESSION['game'])){?>
                    <form method="post" action="<?= Url::toRoute('game/game') ?>">
                        <button class="btn btn-success center-block">Novo Jogo</button>
                    </form>
                <?php }?>
            </div>
                        </div>
                    <div class="col-xs-2">
                        <div class="score-current1" id="r11">
                            <div class="price1" id="p2c1">1</div>
                        </div>
                        <div class="score-current1" id="r12">
                            <div class="price1" id="p2c2">2</div>
                        </div>
                        <div class="score-current1" id="r13">
                            <div class="price1" id="p2c3">3</div>
                        </div>
                        <div class="score-current1" id="r14">
                            <div class="price1" id="p2c4">4</div>
                        </div>
                        <div class="score-current1" id="r15">
                            <div class="price1" id="p2c5">5</div>
                        </div>
                        <div class="score-current1" id="r16">
                            <div class="price1" id="p2c6">6</div>
                        </div>
                        <div class="score-current1" id="r17">
                            <div class="price1" id="p2c7">7</div>
                        </div>
                        <div class="score-current1" id="r18">
                            <div class="price1" id="p2c8">8</div>
                        </div>
                        <div class="score-current1" id="r19">
                            <div class="price1" id="p2c9">9</div>
                        </div>
                    </div>
                </div>

        
                
            </div>
            
</div>
                </div>
                
<script>

    //valores possiveis
    var playerpoint1=1;
    var playerpoint2=2;
    var playerpoint3=3;
    var playerpoint4=4;
    var playerpoint5=5;
    var playerpoint6=6;
    var playerpoint7=7;
    var playerpoint8=8;
    var playerpoint9=9;

    //valores possiveis
    var enemypoint1=1;
    var enemypoint2=2;
    var enemypoint3=3;
    var enemypoint4=4;
    var enemypoint5=5;
    var enemypoint6=6;
    var enemypoint7=7;
    var enemypoint8=8;
    var enemypoint9=9;

    var playertotal=0;
    var enemytotal=0;
    
    //variavel para contar os numeros selecionados
    var count=0;

                

    $( "#dicebutton" ).click(function(e) {
		e.preventDefault();
        //prevenir que dê submit. caso haja erros ele não previne e dá bug. convem ter em atençao
        var playerdice1=$('#dice1').val();
        var playerdice2=$('#dice2').val();

			var playerdice1=Math.floor(Math.random() * 6) + 1  
            var playerdice2=Math.floor(Math.random() * 6) + 1  
            $('#dice1').val(playerdice1);
            $('#dice2').val(playerdice2);

            var html="<div class='col-md-6 col-lg-6 col-sm-12 text-center'>";
            html+="<img  src='http://localhost/weblogic_2020/public/img/diceplayer"+playerdice1+".png' >";
            html+="</div>";
            html+="<div class='col-md-6 col-lg-6 col-sm-12 text-center'>";
            html+="<img  src='http://localhost/weblogic_2020/public/img/diceplayer"+playerdice2+".png' >";
            html+="</div>";
            $('#appenddice').html(html);

            /*if(soma dado != peça do jogador){
                acabou o jogo  bloqueia e muda de jogador
            } else {
                roda o dado
            }*/


            //calcula a soma de pontos
            var sumpoints= playerdice1+playerdice2;
            $('#sumpoints').val(sumpoints);
            
/*             $('.price').each(function(){

                    var color=$(this).css('background-color');
                    if(color=="rgb(255, 255, 255)" || color=="white" || color=="fff"){
                        var id=$(this).attr('id');
                        var string_value=id.replace('point','');
                        if(sumpoints <= 0){
                            
                        }else{
                            if(sumpoints > string_value){
                                
                                        
                            }
                        }

                    }
                

            }); */

            


            //abilita clicar nos botões
            $('#point1').prop('disabled',false);
            $('#point2').prop('disabled',false);
            $('#point3').prop('disabled',false);
            $('#point4').prop('disabled',false);
            $('#point5').prop('disabled',false);
            $('#point6').prop('disabled',false);
            $('#point7').prop('disabled',false);
            $('#point8').prop('disabled',false);
            $('#point9').prop('disabled',false);

            //remove a opção de rodar
            $('#dicebutton').prop('disabled',true);
            $('#gameover').prop('disabled',false);

      
           
    });
    
    
    function checkifpossible(number){
        count++;
        if(number!=0){
            //pegar as variaveis que estão nos inputs
            var sumpoints = $('#sumpoints').val();
            var playerpoints= $('#playerpoints').val();
            var error=0;
            if($('#numberfinish'+number).val()){
                alert('Este número já foi adicionado anteriormente');

            }
            else {

                if($('#numberselected'+number).val()){

                    sumpoints+=number;
                    $('#point'+number).css({"background-color":"white"});

                }else{
                    if(sumpoints >= number){
                
                        //subtrair 
                        sumpoints = sumpoints-number;
                        alert(sumpoints);
                        
                        


                        //adicionar os campos com os pontos escondidos
                        var html="<input type='hidden' value='"+number+"' class='pontos_selecionados' name='numberselected["+count+"]' id='numberselected"+number+"'readonly>";
                        $('#point'+number).css({"background-color":"orange"});

                        $('#appendselected').append(html);
                        $('#sumpoints').val(sumpoints);


                        //soma de pontos -FUNCIONA
                        $('#appendselected').each(function(){
                            var newplayerpoints = 0;
                            $(this).find('input').each(function(){
                            newplayerpoints +=parseInt($(this).val());
                            $('#playerpoints').val(newplayerpoints);
                            });
                        });

                    
                
                        
                        //quanto menor melhor serve para saber quem fez menos pontos
                        var winGame=45;
                        var sub = 0;
                        sub=winGame - $('#playerpoints').val();                    
                        $('#winGame').val(sub);

                    
                
                        
                    

                        if(sumpoints==0){
                            $('.pontos_selecionados').each(function(){
                                var valor=$(this).val();
                                $(this).removeClass('pontos_selecionados');
                                $(this).attr('id','numberfinish'+valor);
                                $('#point'+valor).css({"background-color":"green"});
                            });

                            $('#point1').prop('disabled',true);
                            $('#point2').prop('disabled',true);
                            $('#point3').prop('disabled',true);
                            $('#point4').prop('disabled',true);
                            $('#point5').prop('disabled',true);
                            $('#point6').prop('disabled',true);
                            $('#point7').prop('disabled',true);
                            $('#point8').prop('disabled',true);
                            $('#point9').prop('disabled',true);

                            
                            //remove a opção de rodar
                            $('#dicebutton').prop('disabled',false);
                            $('#gameover').prop('disabled',false);

                            
                        
                            //manda as variaveis para o controlador
                            var formdata = $('#dice_roll_form').serialize();
                                $.ajax({
                                type: 'POST',
                                url: '<?=  URL::toRoute('game/randomdice') ?>', 
                                cache: false,    
                                data: formdata ,
                                success: function(data){  

                                    alert(data);

                                
                                    }
                                });  
                                return false;
                            }
                        
                        else if(sumpoints<0){
                            alert('ERRO NÚMERO MAIOR');
                        }

                    }
                    else{
                        alert('Não é possível selecionar, número superior à soma de dados');
                    } 
                }
            }             

            
        }
        else{
            alert('Valor inválido');
        }


    }

    $( "#gameover" ).click(function(e) {
		e.preventDefault();

        $('#point1').prop('disabled',true);
        $('#point2').prop('disabled',true);
        $('#point3').prop('disabled',true);
        $('#point4').prop('disabled',true);
        $('#point5').prop('disabled',true);
        $('#point6').prop('disabled',true);
        $('#point7').prop('disabled',true);
        $('#point8').prop('disabled',true);
        $('#point9').prop('disabled',true);

                            
        //remove a opção de rodar
        $('#dicebutton').prop('disabled',true);

        
        $('#numberfinish').each(function(){
            var total=0;
            total+=parseInt($('#numberfinish').val());
            $('#pontosfinais').val(total);

        });


        //quanto menor melhor serve para saber quem fez menos pontos
        var winGame=45;
        var sub = 0;
        sub=winGame - $('#playerpoints').val();                    
        $('#winGame').val(sub);


        var formdata = $('#winGame').val();
        $.ajax({
        type: 'POST',
        url: '<?=  URL::toRoute('game/gameoverval') ?>', 
        cache: false,    
        data: formdata ,
        success: function(data){  
            alert(data);
        }
        });  
    });

        

    
    
</script>



