<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header'); ?>
<div class="col-12">
    <table>
        <tr>
            <td><b>Posição</b></td>
            <td><b>Jogador</b></td>
            <td><b>Total Pontos</b></td>
            <td><b>Total Vitórias</b></td>
            <td><b>Total Perdas</b></td>
        </tr>
        <tr>
            <td>1</td>
            <td>Jogador</td>
            <td>Total Pontos</td>
            <td>Total Vitórias</td>
            <td>Total Perdas</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Jogador</td>
            <td>Total Pontos</td>
            <td>Total Vitórias</td>
            <td>Total Perdas</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Jogador</td>
            <td>Total Pontos</td>
            <td>Total Vitórias</td>
            <td>Total Perdas</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Jogador</td>
            <td>Total Pontos</td>
            <td>Total Vitórias</td>
            <td>Total Perdas</td>
        </tr>
        <tr>
            <td>5</td>
            <td>Jogador</td>
            <td>Total Pontos</td>
            <td>Total Vitórias</td>
            <td>Total Perdas</td>
        </tr>
        <tr>
            <td>6</td>
            <td>Jogador</td>
            <td>Total Pontos</td>
            <td>Total Vitórias</td>
            <td>Total Perdas</td>
        </tr>
        <tr>
            <td>7</td>
            <td>Jogador</td>
            <td>Total Pontos</td>
            <td>Total Vitórias</td>
            <td>Total Perdas</td>
        </tr>
        <tr>
            <td>8</td>
            <td>Jogador</td>
            <td>Total Pontos</td>
            <td>Total Vitórias</td>
            <td>Total Perdas</td>
        </tr>
        <tr>
            <td>9</td>
            <td>Jogador</td>
            <td>Total Pontos</td>
            <td>Total Vitórias</td>
            <td>Total Perdas</td>
        </tr>
        <tr>
            <td>10</td>
            <td>Jogador</td>
            <td>Total Pontos</td>
            <td>Total Vitórias</td>
            <td>Total Perdas</td>
        </tr>
    </table>
</div>
<?php Layout::includeLayout('footer')?>