<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header'); ?>
<?php echo "Nome do Jogador" ?>
<div class="col-12">
    <table>
        <tr>
            <td><b>Data início do Jogo</b></td>
            <td><b>Data fim do Jogo</b></td>
            <td><b>Pontos</b></td>
            <td><b>Pontos Adversário</b></td>
            <td><b>Diferença</b></td>
            <td><b>Ganhou</b></td>

        </tr>
        <tr>
            <td>Data início do Jogo</td>
            <td>Data fim do Jogo</td>
            <td>Pontos</td>
            <td>Pontos Adversário</td>
            <td>Diferença</td>
            <td>Ganhou</td>
        </tr>
        <tr>
            <td>Data início do Jogo</td>
            <td>Data fim do Jogo</td>
            <td>Pontos</td>
            <td>Pontos Adversário</td>
            <td>Diferença</td>
            <td>Ganhou</td>
        </tr>
        <tr>
            <td>Data início do Jogo</td>
            <td>Data fim do Jogo</td>
            <td>Pontos</td>
            <td>Pontos Adversário</td>
            <td>Diferença</td>
            <td>Ganhou</td>
        </tr>
        <tr>
            <td>Data início do Jogo</td>
            <td>Data fim do Jogo</td>
            <td>Pontos</td>
            <td>Pontos Adversário</td>
            <td>Diferença</td>
            <td>Ganhou</td>
        </tr>
        <tr>
            <td>Data início do Jogo</td>
            <td>Data fim do Jogo</td>
            <td>Pontos</td>
            <td>Pontos Adversário</td>
            <td>Diferença</td>
            <td>Ganhou</td>
        </tr>
        <tr>
            <td>Data início do Jogo</td>
            <td>Data fim do Jogo</td>
            <td>Pontos</td>
            <td>Pontos Adversário</td>
            <td>Diferença</td>
            <td>Ganhou</td>
        </tr>
        <tr>
            <td>Data início do Jogo</td>
            <td>Data fim do Jogo</td>
            <td>Pontos</td>
            <td>Pontos Adversário</td>
            <td>Diferença</td>
            <td>Ganhou</td>
        </tr>
        <tr>
            <td>Data início do Jogo</td>
            <td>Data fim do Jogo</td>
            <td>Pontos</td>
            <td>Pontos Adversário</td>
            <td>Diferença</td>
            <td>Ganhou</td>
        </tr>
        <tr>
            <td>Data início do Jogo</td>
            <td>Data fim do Jogo</td>
            <td>Pontos</td>
            <td>Pontos Adversário</td>
            <td>Diferença</td>
            <td>Ganhou</td>
        </tr>
        <tr>
            <td>Data início do Jogo</td>
            <td>Data fim do Jogo</td>
            <td>Pontos</td>
            <td>Pontos Adversário</td>
            <td>Diferença</td>
            <td>Ganhou</td>
        </tr>
    </table>
</div>
<?php Layout::includeLayout('footer')?>